### ISSUE TITLE
Game Error

### ISSUE THREAD

**Issue by Reminious** [essium/PlanetWormhole#2]
游戏初期不会发生，但是当生产规模变大就会。一直玩游戏不退出不会发生，但是某一次的读档就会
won't happen at early stages of the game when there were no mass pruduction.
won't happen if continue playing the game without quitting. But sometime you try to load the savegame will cause it.
![image](https://user-images.githubusercontent.com/115909000/196015681-7ff96df5-4c67-4923-aa07-6963746cb62c.png)

**Comment by essium** [comment]
这个我自己也遇到了，应该在1.0.5版里修复了，原因是插件没有正确处理物流塔的删除。
